### ISSUE TITLE
Feature: Implement Reports API

### ISSUE THREAD

**Issue by cdmwebs** [ruckus/quickbooks-ruby#146]
It looks like QBO recently exposed a [reports API](https://developer.intuit.com/docs/0025_quickbooksapi/0050_data_services/reports). I'd like to take a stab at implementing some of the more important reports (Balance Sheet, P&L). 

Any tips as to approach? I was planning to create a Report base class and inherit for the individual reports, but I'm not sure how much is shared.

**Comment by ratbeard** [comment]
I am wondering if anyone has gotten the code in #204 that was merged in to work.  I always get an empty Collection response when I try to use the ReportService.

Looking at the code, ReportService tries to parse the response xml as an collection, which expects the xml response root to be an <IntuitResponse>[1].  As I query the API, and look at the examples inside the spec/fixtures directory, I'm seeing the root node is <Report> [2].  Therefore this `if` branch [3] never gets run, and an empty Collection is always returned.  The tests pass because they only checking the fixture xml contains a certain node, not that the a proper Report model is returned [4].

Maybe Intuits api changed, or as mentioned in the discussion in #204 maybe people are doing something like:

```rb
client.query('BalanceSheet')
xml = Nokogiri.parse(client.last_reponse_xml)
...
```

If thats the only way to get access to the underlying report data, then I don't understand the purpose of Models::Report or code like https://github.com/ruckus/quickbooks-ruby/blob/e3b2cb50ff4605e625c0dffd54b752a753bfa23c/lib/quickbooks/service/base_service.rb#L125-L127 as they are never run.

I plan to work on this so at the minimum client.query returns a Report object with a `body` attribute containing the xml, and just wanted to check in to make sure I'm not missing something; perhaps a way to call Intuits report api and get back a collection of reports?  Otherwise I'll just rip out some of the code that got added and won't worry too much about breaking the api as it currently does not work.

Thanks!
:rat:

[1] https://github.com/ruckus/quickbooks-ruby/blob/e3b2cb50ff4605e625c0dffd54b752a753bfa23c/lib/quickbooks/service/reports.rb#L22
[2] https://github.com/ruckus/quickbooks-ruby/blob/e3b2cb50ff4605e625c0dffd54b752a753bfa23c/spec/fixtures/balancesheet.xml
[3] https://github.com/ruckus/quickbooks-ruby/blob/e3b2cb50ff4605e625c0dffd54b752a753bfa23c/lib/quickbooks/service/base_service.rb#L101-L102
[4] https://github.com/ruckus/quickbooks-ruby/blob/e3b2cb50ff4605e625c0dffd54b752a753bfa23c/spec/lib/quickbooks/service/reports_spec.rb#L25

**Comment by Craggar** [comment]
I use the report service - the xml returns is pretty messy, and not easy to break down into smaller elements (for example it contains 'Rows' objects which contain one or more 'Row', and those can in turn contain one or more 'Rows' or 'Row'). It's not pleasant to work with, but that's exactly what I'm doing: using Nokogiri to break it down, manually parsing the entire response, to extract the data I need.

I only need a couple of headline figures from a couple of very specific reports, though, so haven't revisited it to look at ways to make the response more of a flexible 'entity'.

I have a function (where 'category' is actually just the string "reports") that is something like this:
```
def get_report(category, options={})
  service = Quickbooks::Service::Reports.new
  service.company_id = @token_attributes[:realm_id]
  service.access_token = oauth_access_token
  reportString = options[:report_string]     #report_string is the name of the report
  options.delete(:report_string)             #the options contain additonal options like start_date, end_date, columns, etc
  result = service.query(reportString, {}, options)
  resultXML = service.last_response_xml
end
```
I then have a controller that parses that XML. For example:
```
doc = Nokogiri::XML(report.to_s)
header = doc.at_css "Header"
if header
  headerObject = {}
  headerObject[:time] = getXMLText(header, "Time")
  headerObject[:name] = getXMLText(header, "ReportName")
  #etc
```

With the nesting of row(s) within row(s) it gets pretty messy and recursive after that...

So, yes, it does work, but it could definitely benefit from some attention and improvement, in my opinion.

**Comment by minimul** [comment]
Thanks @Craggar . Let us know @ratbeard if that solves it for you.

With respect to improvements:
Personally, I don't think there is a great solution or abstraction that can
be done here. You basically need to roll up you sleeves with Nokogiri or Oga
and "data mine" and yeah, the XML returned is total spaghetti.
Nokogiri and Oga have advanced CSS3 selector support so it is somewhat easy to
get the data you want e.g.

```
Nokogiri::XML(report.to_s).css('Rows > Header + Rows > Row').each ...
Nokogiri::XML(report.to_s).at('Rows > Header + Rows > Row:last-child').content
```

One improvement could be in `spec/lib/quickbooks/service/reports_spec.rb` is to have advanced
XPath and CSS parsing examples, which could also make its way into the readme.

**Comment by ratbeard** [comment]
Thanks for posting that @Craggar.  I wrote a simple find_row() function yesterday as my use case is similar to yours, I just need to pick out a few 'Total' rows and will ignore the rest, and I don't care how deeply the Rows are nested.  I was thinking this morning I actually want a flattened_rows function that returns a list of all rows without the nesting; then I can loop through each row and grab the data I care about and log out ones I don't.  Just because I'm not sure what all the possible rows customers could have at this point and I want a little bit of debugging help at first.

@minimul I agree that the way nested Rows are gross and providing better API's on top of that might not be worth the effort.  What I was getting at above though is that if the only way to get access to the data is through `last_response_xml` then the following code is dead and should be removed and/or improved:

- ReportService tries to parse the response as a collection, which assumes the response has a root element of <IntuitResponse>.  The actual response has a root of <Report>, so  `query` always returns an empty intuit collection.
- Given that, the `if query_response` check is always nil and so the following code that was added never can be reached: https://github.com/ruckus/quickbooks-ruby/blob/e3b2cb50ff4605e625c0dffd54b752a753bfa23c/lib/quickbooks/service/base_service.rb#L125-L127
- Also given that, there is no way for Models::Report to ever be instantiated.
- Models::Report doesn't make sense how it uses ROXML to declare xml_accessors, but is setting the attributes manually in the code I just linked.  It could instead just declare them as attr_accessors.

So given all that I think my improvements I'm suggesting would be:

- Update ReportService to not try and parse the result as a collection.  Instead it should return an instance of ReportModel.  Update the specs to test that a meaningful object is returned, not that the fixture xml contains a certain node.
- Update ReportModel to not try and use ROXML as it is too awkward to try and map the data out due to the recursive nature of Rows.  It can just expose a property like `body` at a minimum as it currently does.
- Additionally, it _may_ be nice to add some helper methods on to ReportModel like find_row or flattened_rows.  Instead of xpath'ing for ColData's and then mapping their sibling elements, something like:

```rb
report.find_row('Total Cost of Goods Sold')
=> ['Total Cost of Goods Sold', 2000, 2500]
```

That last improvement can lead to a lot of bikeshedding and what not, so any ideas on an api would be very welcome, but regardless of it we should still definitely fix the other issues.

**Comment by ruckus** [comment]
Hi @ratbeard - good questions you raise. I havent used any of the Reporting stuff myself, so I havent noticed this before. You're right in that the `BaseService#parse_collection` has logic in there to handle report model rather than just kick it out raw.

One approach to instructing `query` to not try and parse the XML is to maybe include a `:raw => true` option to `query()`, like:

```ruby
body = client.query('BalanceSheet', :raw => true)
xml = Nokogiri.parse(body)
```

This would then allow us to rip out all of the the lines you highlighted:

https://github.com/ruckus/quickbooks-ruby/blob/e3b2cb50ff4605e625c0dffd54b752a753bfa23c/lib/quickbooks/service/base_service.rb#L125-L127

Anyways, it looks like this area could use some cleaning up and if you want to tackle that it would be much appreciated. Thank you!
