### ISSUE TITLE
Uploading a file (pdf, jpeg, xls....)

### ISSUE THREAD

**Issue by GildedHonour** [ruckus/quickbooks-ruby#151]
I've got a Python script which is supposed to upload files to Quick Books by their API. I've faced into some issues which I couldn't have solved such as "This type can't be consumed" (for application/pdf, xml and others) or when I used "multipart/form-data" it said "Could find no content-disposition header with in a part" or when I'd changed it a bit, it seemed to work well (there were no errors in the response) but the attachments weren't really uploaded.

I'd like to upload a file (pdf, jpeg, xls....) using this gem to make sure it really works well and there is no mistake in the API of Quick Books. I'm familiar with this gem but didn't find a model or service in its source code which looked like the one I was looking for (Attachable, File or something else).

So is there any simple example?

**Comment by GildedHonour** [comment]
I decided to do a pull request. Actually, the tests fail initially in the branch file-upload-prototype, even if I don't touch anything, 32 ones failure. Will you fix them or should I fix them?

**Comment by ruckus** [comment]
I've been working on this in a separate branch: `attachable`. Please review this issue which has more details and a working implementation. Although, right now it doesnt support multiple files.

https://github.com/ruckus/quickbooks-ruby/issues/218

**Comment by GildedHonour** [comment]
Nobody is working on that? I can work?

**Comment by ruckus** [comment]
@GildedHonour I dont understand your question (?) Are you suggesting that you are interested in taking that branch and trying to get multiple files to work? You're totally welcome too, of course.

A big question is how do we deal with failure scenarios? E.g. in a batch of 5 uploads+metadata, what happens if 1 fails but all the other succeed? How should this be reported back to the user? Is an exception raised after the first failure, or do you keep chugging along and pass that information back to the user at the end?

**Comment by GildedHonour** [comment]
Yes. 

I think we should keep trying to upload it giving it a finite number of attempts, when they're exceeded - return an error. Otherwise not to notify the user.

**Comment by ruckus** [comment]
I'm not so sure. If we put the burden on the user to do the iteration over their set of files [to upload] than I think it makes it more explicit and makes our code simpler. Largely, because I imagine that if errors ARE encountered during an upload they are not transient (e.g. network connection) and its because the upload itself is invalid, hence whats the point of trying again for 3-4 times, each time getting the same error?

Ultimately, i think its simpler to only have a one-upload-at-a-time API interface and require the user to do their own iteration, thus doing their own error handling.

**Comment by minimul** [comment]
+1 on the one-upload-at-a-time interface.

**Comment by GildedHonour** [comment]
>> If we put the burden on the user to do the iteration over their set of files [to upload] than I think it makes it more explicit and makes our code simpler. 

No, I mean, the library should handle it itself. The user doesn't have to do anything, maybe only being notified that "something is wrong, attempt number 2...". It's a pretty standard behaviour in most applications.

**Comment by GildedHonour** [comment]
>>Ultimately, i think its simpler to only have a one-upload-at-a-time API interface and require the user to do their own iteration, thus doing their own error handling.

Do you mean leave it as it is now?

**Comment by ruckus** [comment]
@GildedHonour yes, I propose keeping it at one-at-a-time for now.
