### ISSUE TITLE
alias_method_chain is deprecated in rails-5

### ISSUE THREAD

**Issue by MattWalston** [ruckus/quickbooks-ruby#288]
Starting with ruby-2.0 Module#prepend is preferred.  This causes nosy logs.  Do you have any intention on supporting ruby < 2?

**Comment by ruckus** [comment]
Good to know, thanks. No, I would imagine we can stop supporting < 2.0 shortly enough as it seems the rest of the world is moving on.

You want to take a crack at a PR?

**Comment by MattWalston** [comment]
Will do.  Having to refresh my mind on a bit but looking at a solution now.  Should have something later today.

**Comment by dafstone** [comment]
Interested in this also - we're doing an implementation using quickbooks-ruby presently on rails 5/ruby 2.3 and are curious if you're still considering a PR @MattWalston ?

**Comment by minimul** [comment]
Yeah, this definitely has to happen. @dafstone Can you/your team do a PR?

**Comment by dafstone** [comment]
Maybe... we need it.  I'll look at it with my folks this week and see what we can do.

**Comment by MattWalston** [comment]
Not at this time.  No longer using gem.

**Comment by dafstone** [comment]
So I put in a PR for this, but the travis build is failing on some odd Ruby versions. However that looks like it might be a problem on Travis' end, as my colleague says it's saying failures on 1.9.3 and 2.2.0 which test out fine here against the specs. I also can't see the travis build page because I'm getting a connection timeout.  Will check again tomorrow.

**Comment by ruckus** [comment]
This was resolved in 041bd051d9a618450ecddf2b1da876446c116f62  - thanks again!
