### ISSUE TITLE
Batch query request

### ISSUE THREAD

**Issue by bajalovic** [ruckus/quickbooks-ruby#289]
I am trying to use `Quickbooks::Model::BatchRequest` to run several queries in one request.

for example: 

``` ruby
   batch_req = Quickbooks::Model::BatchRequest.new
   batch_req.add('bId1', "Select count(*) from Payments Where CustomerRef = '22'", "query")
   batch_req.add('bId2', "Select count(*) from Payments Where CustomerRef = '33'", "query")
   batch_req.add('bId3', "Select count(*) from Payments Where CustomerRef = '44'", "query")
   # and so on...

   batch_service = Quickbooks::Service::Batch.new
   batch_response = batch_service.make_request(batch_req)
   batch_response.response_items.each do |result|
      puts result.inspect
   end
```

But I am getting error `uninitialized constant String::XML_NODE` caused by `bir.send("#{batch_item.class::XML_NODE.underscore}=", batch_item)` as `batch_item.class` is a String (line 37 in `Quickbooks::Model::BatchRequest`).

In the documentation I found at https://developer.intuit.com/docs/api/accounting/batch I see an example 

``` json
   {
        "bId": "bid4",
        "Query": "select * from estimate"
    }
```

and `add` method generates something like (as I understood)

``` json
{
        "bId": "bid3",
        "operation": "create",
        "Invoice": {
            "Line": [{
                "Amount": 125.00,
                "DetailType": "SalesItemLineDetail",
                "SalesItemLineDetail": {
                    "ItemRef": {
                        "value": "23",
                        "name": "Design"
                    }
                }
            }],
            "CustomerRef": {
                "value": "2"
            }
        }
    }
```

I could not see other method than `add` to create batch query requests. Am I wrong or this is not implemented? 

I would like to have this feature as making a request for each query will take a long time to execute.

**Comment by minimul** [comment]
Its `Select count(*) from Payment` not `Payments`.

**Comment by bajalovic** [comment]
@minimul The problem is in operator for batch requests, not my spelling error while writing the question.

**Comment by ruckus** [comment]
Currently the Batch Request interface is limited to creating objects:

https://github.com/ruckus/quickbooks-ruby#batch-operations

Largely because the 2nd argument to the `Quickbooks::Model::BatchRequest::BatchItemRequest#add` takes a model instance (which does respond to the `XML_NODE` constant) and not an arbitrary query string.

So in a nutshell, the library does not currently support what you're trying to do.

I do admit it would be good functionality to have. The API for this batch interface would need to be updated to take an arbitrary query string.
