### ISSUE TITLE
Plans for JSON support instead of XML?

### ISSUE THREAD

**Issue by bcackerman** [ruckus/quickbooks-ruby#419]
I was looking at https://github.com/minimul/qbo_api#qboapi alternative and they're stating `JSON is the primary data format for the QuickBooks API (v3 and beyond)`.  

It seems `quickbooks-ruby` is XML based. 

Any plans to move to JSON-based?

**Comment by ruckus** [comment]
The current library is XML-based. I looked at implementing JSON and I dont think it could be done in a transparent manner, or at least w/o hacking the core. A lot of the model building AND request/response introspection is based on XML as the payload format.

I think if JSON were to be implemented it would have to be done in a whole new library. A lot of code could / would be shared / copy-pasted, but still.

I asked Intuit if they have plans to deprecate support for XML and they said no. So for the time being we're safe.

**Comment by jaredmoody** [comment]
@ruckus saw in the README you're looking to convert everything to JSON for 1.0 - I'd be happy to put in some time in on this since I use this gem at work and hate XML 😁 

I could use some direction since I don't see anything but the `TaxService` model/service using the base JSON classes which don't have an XML counterpart. Are you wanting to replace existing models/services with JSON models/services or have separate classes - like duplicate models that inherit from `BaseModelJSON` / `BaseServiceJSON`?

Aside: Didn't really know where to put this question, maybe enabling the discussions tab on this repo would be nice?

**Comment by ruckus** [comment]
Hi @jaredmoody I wasn't even aware their was Discussions, interesting, I just enabled them.

I think JSON support would have to be in a total separate gem, I put some thoughts down in this comment:

https://github.com/ruckus/quickbooks-ruby/issues/419#issuecomment-372079400

I don't have plans to implement this other gem anytime soon, largely because there is no pressing requirement that I am aware of and also I don't have availability.

I hope Intuit never deprecates XML support in which case our hands would be tied.

**Comment by jaredmoody** [comment]
I think discussions are fairly new - I haven't used them yet much myself, but seems like a nice place to ask questions without opening an issue :)

> I think JSON support would have to be in a total separate gem

Ah, ok, this section in the README confused me then:

> Ideally, we would like to fully support JSON for all entities and services for the 1.0.0 release. Please jump in and contribute to help that aim.

Thanks a lot for this gem!

**Comment by ruckus** [comment]
@jaredmoody oh hah, I don't remember writing that

> Ideally, we would like to fully support JSON for all entities and services for the 1.0.0 release. Please jump in and contribute to help that aim.

Apologies for the confusion!
