### ISSUE TITLE
Invoice objects cannot be serialized

### ISSUE THREAD

**Issue by bretweinraub** [ruckus/quickbooks-ruby#455]
For example:

      qboi= Invoice.get_service.query("select * from Invoice where DocNumber = '#{number}'").first rescue nil
      # qboi is Quickbooks::Model::Invoice

      yaml = qboi.to_yaml
      reloaded = YAML.load(yaml)

dies with exception

TypeError: allocator undefined for Proc

So there's no way to serialize these objects, which makes caching them rather hard to implement.

**Comment by tyler-boyd** [comment]
Hey @bretweinraub, see https://github.com/ruckus/quickbooks-ruby/issues/138#issuecomment-47554270 for an example of how to cache things.

Here's how I'm caching arbitrary QB API calls (albeit complex). Note that this will NOT work for create/update calls, but you shouldn't be caching those anyway.

```ruby
      def execute_with_caching(cache_key, &block)
        xml = Rails.cache.fetch(cache_key, expires_in: 2.hours) do
          cached = false
          got = yield
          next nil if got.nil?
          if got.is_a?(Array)
            next got.map(&:to_xml).map(&:to_s)
          end
          got.to_xml.to_s
        end
        Rails.cache.delete(cache_key) if !xml.present?
        return nil if xml.nil?
        if xml.is_a?(Array)
          return xml.map { |el| model.from_xml(el) }
        else
          return model.from_xml(xml)
        end
      end

# ...

clients = execute_with_caching("some-key") do
  qb_clients_service.all
end
```

**Comment by ruckus** [comment]
@tyler-boyd thanks for your code example.

@bretweinraub interesting use-case; and I had not encountered this before because I have not cached these Ruby objects or attempted to do so.

But I am not surprised these complex objects could not be serialized. In my personal experience I have seen issues with relying on Ruby Marshal library which is the default serialization framework. The biggest issue I have seen is the serialization format seems to be ruby version specific (eg. Ruby 2.5.8 vs 2.6.0) and if you are running multiple ruby versions then you can have issues loading/unloading objects.

As such I think @tyler-boyd approach is correct in that he serializes the object to a more vanilla string value, in this case XML. 

Personally I stay away from Ruby Marshal and serialize to JSON (or XML) because its bit me in the past. But thats just my own experience, YMMV.

**Comment by bretweinraub** [comment]
In my example I was writing to a YAML string.  But yeah we can close this!   Thx
