### ISSUE TITLE
Support for OAuth2 disconnect/revoke

### ISSUE THREAD

**Issue by Zajn** [ruckus/quickbooks-ruby#467]
Hi! We've been using this gem with much success, so thank you all for your work on it! 

We're in the process of migrating to OAuth 2 for authentication to QuickBooks Online, and we've hit a snag on the`389-oauth2` branch. There doesn't seem to be a way to revoke or disconnect the access token. 

Our OAuth 1.0 code simply called `Quickbooks::Service::AccessToken#disconnect` and all was well. Authenticating with OAuth 2 and attempting to disconnect using the same method yields an error from Intuit:

```xml
<?xml version="1.0" encoding="utf-8"?>
<PlatformResponse xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://platform.intuit.com/api/v1">
  <ErrorMessage>Authentication required</ErrorMessage>  
  <ErrorCode>22</ErrorCode>
  <ServerTime>2019-04-22T19:05:08.3346136Z</ServerTime>
</PlatformResponse>
```

I'm assuming this is because we're hitting an OAuth 1.0 service and trying to disconnect our OAuth 2 token from it, and that service doesn't see our user as authenticated. Is that correct?

Are there currently any methods to disconnect or revoke an OAuth 2 token implemented? Or perhaps I am just doing something wrong, or using the wrong service to disconnect my token?

**Comment by ruckus** [comment]
Thanks for the heads up.

According to the Intuit OAuth2 docs:

https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/oauth-2.0#revoke-token-disconnect

The URL is different.  I just pushed this commit which should address is:

https://github.com/ruckus/quickbooks-ruby/commit/1e37cb416c9b7f1e0d303fe9da2965a170987526

Give it a whirl please?

**Comment by Zajn** [comment]
Thank you for the lightning-fast response!

That didn't work, unfortunately. It failed with a very cryptic error:

```
Quickbooks::IntuitRequestException (:
	):
```

I think it's due to the fact that not only did the URL change, but the HTTP verb did too. It's now a POST instead of a GET, according to Intuit's documentation.

This is the REST example they provide:

```
POST https://developer.api.intuit.com/v2/oauth2/tokens/revoke HTTP/1.1
Accept: application/json
Authorization: Basic UTM0dVBvRDIwanp2OUdxNXE1dmlMemppcTlwM1d2
    NzRUdDNReGkwZVNTTDhFRWwxb0g6VEh0WEJlR3dheEtZSlVNaFhzeGxma1l
    XaFg3ZlFlRzFtN2szTFRwbw==
Content-Type: application/json

{
    "token": "{bearerToken or refreshToken}"
}
```
Where the `Authorization` header is generated as such:

```
"Basic " + base64encode(client_id + ":" + client_secret)
```

That seems much more complex, since you need to know the `client_id` and `client_secret` to generate the Authorization header. I was able to get a little further by making a few changes in `access_token.rb`:

```diff
@@ -26,12 +28,15 @@ module Quickbooks
 
         disconnect_url = nil
 
         if oauth_v1?
           disconnect_url = DISCONNECT_URL_OAUTH1
+          response = do_http_get(disconnect_url)
         elsif oauth_v2?
           disconnect_url = DISCONNECT_URL_OAUTH2
+          headers = { 'Authorization' => 'Basic ' + Base64.encode64("#{oauth.client.id}:#{oauth.client.secret}")}
+          response = do_http_post(disconnect_url, '', { token: oauth.token }, headers)
         end
-        response = do_http_get(disconnect_url)
 
         if response
           code = response.code.to_i
```

but this fails with an `AuthorizationError` again, and I'm not sure why. I might be generating the `Authorization` header incorrectly. I'm also not 100% sure if the bearer token in their example is identical to the access token, or if it's a combination of `Bearer #{access_token}`

**Comment by ruckus** [comment]
Doh, yeah POST vs GET. 

Looking at what you provided more closely and comparing it to the docs -- it looks like you're doing it correctly.

Although this is a good question:

> identical to the access token, or if it's a combination of Bearer #{access_token}

Ultimately I would start debugging by enabling logging or hooking it up to HTTP Proxy like Charles

https://github.com/ruckus/quickbooks-ruby#logging

This would allow you to look at the raw HTTP request/response. What I'm *wondering* is that since the HTTP POST is made thru the OAuth instance - if its hijacking your provided `Authorization` header with its own value (thinking that you're asking it do a "normal" HTTP POST where it imbues with the oauth auth stuff).

But in this case its not a normal HTTP POST, its fairly raw and maybe we dont want it to go thru the OAuth instance. 

If we can nail down thats what is happening then we should be able to use just build a pretty raw HTTP POST call that skips the OAuth instance. Just basically calling Faraday connection directly. There is no accessor for the underlying connection but we can add an accessor method in `BaseService` that gives us access to the underlying `@oauth.client.connection`

**Comment by ruckus** [comment]
For oauth2 enabling HTTP Proxy inspection is done like

```ruby
oauth_params = {
  :site => "https://appcenter.intuit.com/connect/oauth2",
  :authorize_url => "https://appcenter.intuit.com/connect/oauth2",
  :token_url => "https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer",
  :connection_opts => {
    :proxy => "http://127.0.0.1:8888"
  }
}
oauth_client = OAuth2::Client.new(client_id, client_secret, oauth_params)
```

**Comment by Zajn** [comment]
> Ultimately I would start debugging by enabling logging or hooking it up to HTTP Proxy like Charles

Ok, great. I'll give this a try tonight and see what I can come up with. I'll get back to you with my results. Thanks again for your help and quick turn-around time!

**Comment by Zajn** [comment]
I haven't been able to get a HTTP proxy setup successfully without Faraday complaining about a self-signed cert.

I tried to do the POST request through Postman and leave everything other than my credentials out of the equation, and I _still_ can't get a revoke to work correctly. So it seems like there's something wrong with:

1. The `Authorization` header
or
2. The token that I'm providing in the body

I have an open ticket with Intuit to see if they can see anything that I'm doing wrong in my POST request.

**Comment by Zajn** [comment]
@ruckus You were right about the OAuth instance hijacking the Authorization header!

I finally got a 200 from Intuit after I debugged all the way through to the point where the OAuth 2 instance was creating the options for the POST request, and I manually updated the Authorization header to be what Intuit expects it to be. Once I did that, I got a 200 back. 

My code failed with a `Quickbooks::IntuitRequestException`, and an error: `: <?xml version="1.0"?>`. I think _maybe_ because the response from Intuit is coming back as JSON, and it's being interpreted as XML instead? I'm not sure.

**Comment by brianhenryhf** [comment]
@Zajn re:
> I haven't been able to get a HTTP proxy setup successfully without Faraday complaining about a self-signed cert.

I'd amend @ruckus 's code like this:
```ruby
oauth_params = {
  :site => "https://appcenter.intuit.com/connect/oauth2",
  :authorize_url => "https://appcenter.intuit.com/connect/oauth2",
  :token_url => "https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer",
  :connection_opts => {
    :proxy => "http://127.0.0.1:8888",
    :ssl => { verify: false } # add this
  }
}
oauth_client = OAuth2::Client.new(client_id, client_secret, oauth_params)
```

**Comment by jaredmoody** [comment]
I also hit this issue today - is there a commit coming or PR pending to address the get vs post issue? Seems like a quick fix...

**Comment by jaredmoody** [comment]
Sorry, I didn't quite understand the nature of the problem at first.

Instead of a proxy, I just turned on `Quickbooks.log = true` so that the request headers would be printed.  

That let me see the authorization header being overwritten, which I tracked down to confirm; it happens here: https://github.com/oauth-xx/oauth2/blob/master/lib/oauth2/access_token.rb#L153

So, to disconnect we need to not make the post request through the oauth access token.

I used Faraday directly to make this work:

```ruby
def disconnect
  result = nil

  if oauth_v1?
    response = do_http_get(DISCONNECT_URL_OAUTH1)
  elsif oauth_v2?
    conn = Faraday.new do |faraday|
             faraday.basic_auth oauth.client.id, oauth.client.secret
           end

    response = conn.post(DISCONNECT_URL_OAUTH2, { token: oauth.refresh_token })
  end

  ...
end

```

I'll submit a PR shortly.

**Comment by ruckus** [comment]
Closing via PR from @jaredmoody 

https://github.com/ruckus/quickbooks-ruby/commit/27c1ecdc303be858e2b573c5cca656c4b4a63fba

**Comment by Zajn** [comment]
Hey guys! The disconnect works great, but introduces a bug when it tries to parse the now empty response to XML:

```ruby
response.plain_body
=> ""
result = Quickbooks::Model::AccessTokenResponse.from_xml(response.plain_body)
NoMethodError: undefined method `root' for nil:NilClass
from /Users/zach/.gem/ruby/2.6.2/gems/roxml-4.0.0/lib/roxml/xml/parsers/nokogiri.rb:52:in `default_namespace'
```

I'd be happy to create a PR to fix this, but what would do you think makes sense to return here?

The response from Intuit has no body, so does it make sense to just return an `{}`?

**Comment by jaredmoody** [comment]
I'm happy to fix this since I broke it :P

Couple additional thoughts:

1. This seems a symptom of the test responses not matching what's actually returned by the API. I suppose we could modify the stubbed response in the spec to return `""` - but maybe something like vcr should be used to actually record the response from the api.

2. I think by default the response from the API is json, so not sure that `Quickbooks::Model::AccessTokenResponse.from_xml` makes sense? I'll check to see if this endpoint supports XML, I think that should make everything just work.

**Comment by Zajn** [comment]
> I'm happy to fix this since I broke it :P

Works for me! 😄 

> I suppose we could modify the stubbed response in the spec to return "" - but maybe something like vcr should be used to actually record the response from the api.

I started down the route of just returning `""`, but vcr would definitely give a more accurate response.

> I think by default the response from the API is json

I think that's the _only_ response now. I can't find a source on that, but it doesn't seem they support anything but JSON for their OAuth2 endpoints.

I agree that there should ideally be a new class for OAuth2 `AccessTokenResponse`s.

Thank you for looking into this, and let me know if I can help in anyway!

**Comment by jaredmoody** [comment]
> I think that's the only response now. I can't find a source on that, but it doesn't seem they support anything but JSON for their OAuth2 endpoints.

I think you're correct, I couldn't get the endpoint to return anything but `""` in the body.

Since today is my first day contributing to this gem I didn't want to introduce vcr myself yet, but I think it would be beneficial. Same for reworking `AccessTokenResponse` or introducing new response class.

See PR #470
